server:
  port: 8020
spring:
  application:
    name: students
  datasource:
    name: orderingsystem
    url: jdbc:mysql://localhost:3306/students?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wangyuhang724
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wyh.model
